// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID           int32            `json:"id"`
	FromWalletID pgtype.UUID      `json:"from_wallet_id"`
	ToWalletID   pgtype.UUID      `json:"to_wallet_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Currency     string           `json:"currency"`
	Description  string           `json:"description"`
}

type Wallet struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Balance   pgtype.Numeric   `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Currency  string           `json:"currency"`
	IsActive  bool             `json:"is_active"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
